# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d634d5664ad40f8baabfe2f9e6e1194b87e49ab6cb11739791e1f4aba7fedb7a61956dfefb6bed1bffeeb6c0d99dfd96041737f01b701269cecfdd9c2d14511d

test:
  secret_key_base: 5cc471ffee549ef6c77aefe70f0b82896018c1f3d61e6b658c09fabf032f5df9751819c68c2272212ed8c08a5ee2c76567cb45928937a55ad294aa9327ead122

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
